routes/web.php
Route::get('/shoppingcart/{id_store}/{id_table}', 'TableController@shoppingcart' );
Route::post('/shoppingcart/makeorder', "TableController@cart");
Route::post('/shoppingcart/DB_add_to_cart', "TableController@DB_add_to_cart" );
Route::post('/shoppingcart/DB_delete_order', "TableController@DB_delete_order");
Route::post('/shoppingcart/table_alert', "TableController@table_alert");
Route::post('/shoppingcart/paidCart', "TableController@paidCart");
Route::post('/shoppingcart/reject_order', "TableController@reject_order");

Route::get('/invoice', 'PdfController@PDF')->name('invoice');
Route::get('/shoppingcart/paid', 'TableController@paid');
Route::post('shoppingcart/DB_cancel_cart', 'TableController@DB_cancel_cart');



/* Route::get('storage-link', function(){
    if(file_exists(public_path('storage'))){
        return 'The "public storage" directory already exist';
    }
    app('files')->link(
        storage_path('app/public'), public_path('storage')
    );
    return 'The [public/storage] directory has been linked';
}); */


// Main screen
Route::get('/store/register', "Home\StoreHomeController@register")->name('store_register');
Route::post('/store/register', "Home\StoreHomeController@RegisterNewStore")->name('register_new_store');


Route::get('/store/pricing', "Home\StoreHomeController@pricing")->name('store_pricing');
Route::get('/store/privacy', "Home\StoreHomeController@privacy")->name('privacy');


Route::get('/', "Home\StoreHomeController@home")->name('home');

Route::get('/store/{view_id}', "Home\StoreHomeController@index")->name('view_store');
Route::get('/store/cart/{all}', "Home\StoreHomeController@index")->where('all', '.*');
Route::get('/store/{view_id}/product/details/{product_id}', "Home\StoreHomeController@index")->where('all', '.*');



Route::get('/store/view/qr/{view_id}/print','Home\QrController@print')->name('download_qr');
Route::get('/store/view/tblqr/{view_id}/{table_no}/print','Home\QrController@tblprint')->name('download_tblqr');
// admin side
Route::get('/admin/dashboard', 'AdminPageController@dashboard')->name('dashboard');
Route::get('/admin/dashboard/store/add', 'AdminPageController@add_store')->name('add_store');
Route::get('/admin/dashboard/store/all', 'AdminPageController@all_stores')->name('all_stores');
Route::get('/admin/dashboard/store/{id}/edit', 'AdminPageController@edit_stores')->name('edit_stores');
Route::post('/admin/dashboard/store/create', 'Admin\StoreController@create')->name('create_store');
Route::post('/admin/dashboard/store/{id}/update',"Admin\StoreController@update")->name('update_store');


Route::get('/admin/dashboard/sliders', 'AdminPageController@all_slider')->name('all_sliders');
Route::get('/admin/dashboard/slider/add', 'AdminPageController@add_slider')->name('add_slider');
Route::get('/admin/dashboard/slider/{id}/update', 'AdminPageController@update_slider')->name('update_slider');

Route::post('/admin/dashboard/slider/add', 'Admin\SliderController@add_slider')->name('upload_slider');
Route::patch('/admin/dashboard/slider/{id}/update', 'Admin\SliderController@update_slider')->name('edit_slider');
Route::delete('/admin/dashboard/slider/delete', 'Admin\SliderController@delete_slider')->name('delete_slider');


Route::get('/admin/dashboard/settings', 'AdminPageController@settings')->name('settings');
Route::post('/admin/dashboard/settings', 'Admin\ApplicationController@update_account')->name('update_settings');
Route::post('/admin/dashboard/payment/settings/update', 'Admin\ApplicationController@update_payment_settings')->name('update_payment_settings');

Route::get('/admin/dashboard/settings/account', 'AdminPageController@account_settings')->name('account_settings');

Route::get('/admin/dashboard/settings/payment', 'AdminPageController@paymentsettings')->name('paymentsettings');
Route::post('/admin/dashboard/settings/payment', 'Admin\ApplicationController@update_account_settings')->name('update_account_settings');

Route::get('/admin/dashboard/settings/privacy', 'AdminPageController@privacy_policy')->name('privacy_policy');
Route::post('/admin/dashboard/settings/privacy/update', 'Admin\ApplicationController@update_privacy_policy')->name('update_privacy_policy');

Route::get('/admin/dashboard/settings/cache', 'AdminPageController@cache_settings')->name('cache_settings');

// Remove application cache



//
//subscription

Route::get('/admin/dashboard/subscription/all', 'AdminPageController@subscription')->name('all_subscription');
Route::get('/admin/dashboard/subscription/add', 'AdminPageController@addsubscription')->name('add_subscription');
Route::get('/admin/dashboard/subscription/{id}/edit', 'AdminPageController@editsubscription')->name('edit_subscription');
Route::patch('/admin/dashboard/subscription/{id}/edit', 'Admin\SubscriptionController@editsubscription')->name('update_subscription');

Route::post('/admin/dashboard/subscription/add', 'Admin\SubscriptionController@add_subscription')->name('add_new_subscription');



//Route::get('/store/{view_id}', "Home\StoreHomeController@index")->name('view_store');
Route::any('/account/{all}/',"Home\UserController@index")->where('all', '.*');








Route::get('/restaurants/addproducts',function (){
    return view('restaurants.addproducts');
});

Route::get('/restaurants/orders',function (){
    return view('restaurants.orders');
});

Route::get('/restaurants/vieworder',function (){
    return view('restaurants.vieworder');
});


Route::prefix('store/auth')
    ->as('store.')
    ->group(function() {
        Route::namespace('Auth\Login')
            ->group(function() {
                Route::get('login', 'StoreController@showLoginForm')->name('login');
                Route::post('login', 'StoreController@login')->name('login');
                Route::post('logout', 'StoreController@logout')->name('logout');
            });
    });

Route::prefix('/admin/store/') ->as('store_admin.')
    ->group(function () {
        //JS - ROUTES
        Route::get('thetable/{id_table}', 'TableController@thetable')->name('thetable');
        Route::post('daily_report/', 'TableController@daily_report')->name('daily_report');

        Route::get('dashboard',"RestaurantAdminPageController@index")->name('dashboard');

        //orders
        Route::get('orders',"RestaurantAdminPageController@orders")->name('orders');
        Route::get('orders/details/{id}',"RestaurantAdminPageController@view_order")->name('view_order');

        Route::patch('orders/status/{id}/update',"StoreAdmin\UpdateOrderStatusController@updateStatus")->name("update_order_status");
        Route::get('categories',"RestaurantAdminPageController@categories")->name('categories');
        Route::get('addcategories',"RestaurantAdminPageController@addcategories")->name('addcategories');
        Route::get('editcategories/{id}/update', 'RestaurantAdminPageController@update_category')->name('update_category');
        Route::get('products',"RestaurantAdminPageController@products")->name('products');
        Route::get('addproducts',"RestaurantAdminPageController@addproducts")->name('addproducts');
        Route::get('editproducts/{id}/update', 'RestaurantAdminPageController@update_products')->name('update_products');

//        Route::get('userChangeStatus', 'RestaurantAdminPageController@userChangeStatus');

        Route::post('addcategories', 'StoreAdmin\CategoryController@add_category')->name('addcategories');
        Route::patch('editcategories/{id}/update', 'StoreAdmin\CategoryController@update_category')->name('edit_category');
        Route::post('addproducts', 'StoreAdmin\ProductController@addproducts')->name('addproducts');
        Route::patch('editproducts/{id}/update', 'StoreAdmin\ProductController@edit_products')->name('edit_products');
        Route::delete('products/delete', 'StoreAdmin\ProductController@delete_product')->name('delete_product');
        Route::delete('categories/delete', 'StoreAdmin\CategoryController@delete_category')->name('delete_category');


        Route::get('/alltables', 'RestaurantAdminPageController@tables')->name('all_tables');

        Route::get('addnewtable', 'RestaurantAdminPageController@add_table')->name('add_tables');
        Route::post('addnewtable', 'StoreAdmin\TableController@add_table')->name('add_new_table');

        Route::get('alltables/{id}/edit', 'RestaurantAdminPageController@edit_table')->name('edit_table');
        Route::patch('alltables/{id}/edit', 'StoreAdmin\TableController@edit_table')->name('edit_table');


        Route::get('/banner', 'RestaurantAdminPageController@banner')->name('banner');
        Route::get('addbanner',"RestaurantAdminPageController@addbanner")->name('addbanner');
        Route::post('addbanner',"StoreAdmin\StoreSliderController@add_slider")->name('add_banner');

        Route::get('/banner/{id}/edit', 'RestaurantAdminPageController@banneredit')->name('banneredit');
        Route::patch('banner/{id}/edit', 'StoreAdmin\StoreSliderController@update_slider')->name('update_slider');
        Route::delete('banner/delete', 'StoreAdmin\StoreSliderController@delete_slider')->name('delete_slider');

        Route::get('/subscription/plans', 'RestaurantAdminPageController@subscription_plans')->name('subscription_plans');
            Route::get('/subscription/plans/history', 'RestaurantAdminPageController@subscription_history')->name('subscription_history');

        Route::post('/subscription/compete/payment', 'StoreAdmin\CheckoutController@completeSubscriptionPayment')->name('subscription_complete_payment');
        Route::get('/subscription/compete/payment/complete', 'StoreAdmin\CheckoutController@completeSubscriptionAfterPayment')->name('subscription_after_complete_payment');

        Route::get('/settings', 'RestaurantAdminPageController@settings')->name('settings');
        Route::post('/settings/update', 'StoreAdmin\AccountSettings@update_store_settings')->name('update_store_settings');


});



Auth::routes();

resources/views/restaurants/layouts/app.blade.php

















<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Restaurants Login</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">


    <link href={{asset('assets/css/lib/calendar2/pignose.calendar.min.css')}} rel="stylesheet"/>
    <link href={{asset('assets/css/lib/chartist/chartist.min.css')}} rel="stylesheet"/>
    <!-- Styles -->
    <link href={{asset('assets/css/lib/owl.carousel.min.css')}} rel="stylesheet"/>
    <link href={{asset("assets/css/lib/font-awesome.min.css")}} rel="stylesheet">
    <link href={{asset("assets/css/lib/themify-icons.css")}} rel="stylesheet">
    <link href={{asset("assets/css/lib/menubar/sidebar.css")}} rel="stylesheet">
    <link href={{asset("assets/css/lib/bootstrap.min.css")}} rel="stylesheet">
    <link href={{asset("assets/css/lib/unix.css")}} rel="stylesheet">
    <link href={{asset("assets/css/style.css")}} rel="stylesheet">

</head>

<body>
@yield('content')


<!-- jquery vendor -->
<script src={{asset("assets/js/lib/jquery.min.js")}}></script>
<!-- nano scroller -->
<script src={{asset("assets/js/lib/jquery.nanoscroller.min.js")}}></script>
<!-- sidebar -->
<script src={{asset("assets/js/lib/menubar/sidebar.js")}}></script>
<!-- bootstrap -->
<script src={{asset("assets/js/lib/bootstrap.min.js")}}></script>


<script src={{asset("assets/js/lib/calendar-2/moment.latest.min.js")}}></script>
<!-- scripit init-->
<script src={{asset("assets/js/lib/calendar-2/semantic.ui.min.js")}}></script>

<!-- scripit init-->
<script src={{asset("assets/js/lib/calendar-2/prism.min.js")}}></script>

<!-- scripit init-->
<script src={{asset("assets/js/lib/calendar-2/pignose.calendar.min.js")}}></script>

<!-- scripit init-->
<script src={{asset("assets/js/lib/calendar-2/pignose.init.js")}}></script>
<script src={{asset("assets/js/lib/preloader/pace.min.js")}}></script>

<script src={{asset("assets/js/scripts.js")}}></script>

</body>

</html>

resources/views/restaurants/layouts/notification.blade.php
@if($notification!=NULL)

<div class="card">
                <div class="modal fade " id="modal-notification" tabindex="-1" role="dialog" aria-labelledby="modal-notification" aria-hidden="true" >
                    <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
                        <div class="modal-content bg-gradient-danger">
                            <div class="modal-header">
                                <h6 class="modal-title" id="modal-title-notification">Your attention is required</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="py-3 text-center">
                                    <i class="ni ni-bell-55 ni-3x"></i>
                                    <h4 class="heading mt-4">{{$notification['head']}}</h4>
                                    <p>{{$notification['sub_head']}}</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" onclick="document.getElementById('action-form').submit();" class="btn btn-white">{{$notification['route_submit_button_name']}}</button>
                                <button type="button" class="btn btn-link text-white ml-auto" data-dismiss="modal" >Close</button>
                            </div>
                            <form method="get" id="action-form" action="{{$notification['route'] !=NULL ?route($notification['route']):NULL}}"/>
                        </div>
                    </div>
                </div>
            </div>
@endif

resources/views/restaurants/layouts/restaurantslayout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{csrf_token()}}" />

    <title>{{ Auth::user()->store_name }}</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <link href={{asset('assets/css/lib/calendar2/pignose.calendar.min.css')}} rel="stylesheet"/>
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href={{asset('new/vendor/nucleo/css/nucleo.css')}} type="text/css">
    <link rel="stylesheet" href={{asset('new/vendor/@fortawesome/fontawesome-free/css/all.min.css')}} type="text/css">
    <!--  CSS -->
    <link rel="stylesheet" href={{asset('new/css/argon.css?v=1.1.0')}} type="text/css">

    <!-- Page plugins -->
    <link rel="stylesheet" href={{asset('new/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css')}}>
    <link rel="stylesheet" href={{asset('new/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css')}}>
    <link rel="stylesheet" href={{asset('new/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css')}}>

    <!-- Page plugins -->
    <link rel="stylesheet" href={{asset('new/vendor/select2/dist/css/select2.min.css')}}>
    <link rel="stylesheet" href={{asset('new/vendor/quill/dist/quill.core.css')}}>

    <link rel="stylesheet" href={{asset('new/css/chef.css')}} type="text/css">

</head>

<body>


@include('restaurants.layouts.sidebar')



<!-- Main content -->
<div class="main-content" id="panel">
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-gradient-warning border-bottom">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Search form -->

                <!-- Navbar links -->
                <ul class="navbar-nav align-items-center ml-md-auto">
                    <li class="nav-item d-xl-none">
                        <!-- Sidenav toggler -->
                        <div class="pr-3 sidenav-toggler sidenav-toggler-light" data-action="sidenav-pin" data-target="#sidenav-main">
                            <div class="sidenav-toggler-inner">
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                            </div>
                        </div>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="ni ni-ungroup"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default dropdown-menu-right">
                            <div class="row shortcuts px-4">
                                <a href="" class="col-4 shortcut-item">
                    <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                      <i class="ni ni-album-2"></i>
                    </span>
                                    <small>Sliders</small>
                                </a>
                                <a href="" class="col-4 shortcut-item">
                    <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                      <i class="ni ni-bag-17"></i>
                    </span>
                                    <small>Add Store</small>
                                </a>
                                <a href="" class="col-4 shortcut-item">
                    <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                      <i class="ni ni-basket"></i>
                    </span>
                                    <small>View Stores</small>
                                </a>



                            </div>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav align-items-center ml-auto ml-md-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <img alt="Image placeholder" src={{asset("assets/images/avatar/1.jpg")}}>
                  </span>
                                <div class="media-body ml-2 d-none d-lg-block">
                                    <span class="mb-0 text-sm  font-weight-bold" style="color: #000000;">{{ Auth::user()->store_name }}</span>
                                </div>
                            </div>
                        </a>

                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="header pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">


                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->


@yield("restaurantcontant")


<!-- Page content -->



</div>

<script src={{asset("new/vendor/jquery/dist/jquery.min.js")}}></script>
<script src={{asset("new/vendor/bootstrap/dist/js/bootstrap.bundle.min.js")}}></script>
<script src={{asset("new/vendor/js-cookie/js.cookie.js")}}></script>
<script src={{asset("new/vendor/jquery.scrollbar/jquery.scrollbar.min.js")}}></script>
<script src={{asset("new/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js")}}></script>
<script src={{asset("new/vendor/chart.js/dist/Chart.min.js")}}></script>
<script src={{asset("new/vendor/chart.js/dist/Chart.extension.js")}}></script>
<script src={{asset("new/vendor/jvectormap-next/jquery-jvectormap.min.js")}}></script>
<script src={{asset("new/js/vendor/jvectormap/jquery-jvectormap-world-mill.js")}}></script>
<script src={{asset("new/js/argon.js?v=1.1.0")}}></script>





<script src={{asset("new/vendor/select2/dist/js/select2.min.js")}}></script>
<script src={{asset("new/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")}}></script>
<script src={{asset("new/vendor/nouislider/distribute/nouislider.min.js")}}></script>
<script src={{asset("new/vendor/quill/dist/quill.min.js")}}></script>
<script src={{asset("new/vendor/dropzone/dist/min/dropzone.min.js")}}></script>
<script src={{asset("new/vendor/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js")}}></script>
<script src={{asset("assets/js/printthis.js")}}></script>



<script>
    $('#printButton').on('click',function(){
        $('#printThis').printThis();
    })
    //on single click, accpet order and disable button
    $('body').on("click", ".acceptOrderBtn", function(e) {
        $(this).addClass('pointer-none');
    });
    //on Single click donot cancel order
    $('body').on("click", ".cancelOrderBtn", function(e) {
        return false;
    });
    //cancel order on double click
    $('body').on("dblclick", ".cancelOrderBtn", function(e) {
        $(this).addClass('pointer-none');
        window.location = this.href;
        return false;
    });
</script>
<script>
    $('#modal-notification').modal('show')
</script>
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{$publishableKey ?? ""}}');
    var checkoutButton = document.getElementById('checkout-button');

     function triggerPayment(id) {
        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch('{{route("store_admin.subscription_complete_payment")}}'+"?plan_id="+id, {
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token()}}",
            },
            body: JSON.stringify({plan_id:id})
        })
            .then(function(response) {
                return response.json();
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
            })
            .then(function(result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function(error) {
                console.log("err");
                alert('PAYMENT_ERROR #404');
                console.error('Error:', error);
            });
    }
</script>
</body>

</html>







resources/views/restaurants/layouts/sidebar.blade.php



<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header d-flex align-items-center">
            <a class="navbar-brand" >
               <h2>{{ Auth::user()->store_name }}</h2>
            </a>
            <div class="ml-auto">
                <!-- Sidenav toggler -->
                <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                    <div class="sidenav-toggler-inner">
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">




                    <li {{Route::currentRouteNamed('store_admin.dashboard')? 'class=nav-item active':null }}>
                        <a class="nav-link"   href="{{route('store_admin.dashboard')}}">
                            <i class="ni ni-books text-blue"></i>
                            <span class="nav-link-text">Dashboard</span>
                        </a>
                    </li>




                    <li {{ Request::is("admin/store/orders*") ? 'class=nav-item active':null}} >
                        <a  class="nav-link"   href="{{route('store_admin.orders')}}">
                            <i class="ni ni-cart text-green"></i>
                            <span class="nav-link-text">Orders</span>
                        </a>
                    </li>



{{--                     <li {{Route::currentRouteNamed('store_admin.banner')? 'class=nav-item active':null }} >
                        <a  class="nav-link"   href="{{route('store_admin.banner')}}">
                            <i class="ni ni-bullet-list-67 text-yellow"></i>
                            <span class="nav-link-text">Promo Banner</span>
                        </a>
                    </li> --}}


                    <li class="nav-item">
                        <a class="nav-link" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-examples">
                            <i class="ni ni-box-2 text-orange"></i>
                            <span class="nav-link-text">Inventory</span>
                        </a>
                        <div class="collapse" id="navbar-examples">
                            <ul class="nav nav-sm flex-column">
                                <li {{ Request::is("admin/store/categories*") ? 'class=nav-item active':null}} class="nav-item">
                                    <a href="{{route('store_admin.categories')}}" class="nav-link">Category</a>
                                </li>
                                <li {{ Request::is("admin/store/products*") ? 'class=nav-item active':null}} class="nav-item">
                                    <a href="{{route('store_admin.products')}}" class="nav-link">Products</a>
                                </li>

                            </ul>
                        </div>
                    </li>


                    <li {{Route::currentRouteNamed('store_admin.all_tables')? 'class=nav-item active':null }} >
                        <a  class="nav-link"   href="{{route('store_admin.all_tables')}}">
                            <i class="ni ni-bullet-list-67 text-info"></i>
                            <span class="nav-link-text">Tables</span>
                        </a>
                    </li>

{{--                     <li class="nav-item">
                        <a  class="nav-link" href="{{route('download_qr',[Auth::user()->view_id])}}">
                            <i class="ni ni-cloud-download-95 text-green"></i>
                            <span class="nav-link-text"> Print Qr-Code</span>
                        </a>
                    </li> --}}
                    <li class="nav-item">
                        <a  class="nav-link" href="{{route('store_admin.subscription_plans')}}">
                            <i class="ni ni-spaceship text-flat-darker"></i>
                            <span class="nav-link-text"> Subscription Plans</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a  class="nav-link" href="{{route('store_admin.settings')}}">
                            <i class="ni ni-settings text-blue"></i>
                            <span class="nav-link-text"> Settings</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a  class="nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="ni ni-lock-circle-open text-pink"></i>
                            <span class="nav-link-text"> Logout</span>
                        </a>
                    </li>
                    <form id="logout-form" action="{{route('store.logout')}}" method="POST" style="display: none;">
                        {{csrf_field()}}
                    </form>
                </ul>




                </ul>
                <!-- Divider -->



            </div>
        </div>
    </div>
</nav>